### PR TITLE
feat: add some aws codebuild env vars.

### PR DESCRIPTION
**Pull request by dougch**
AWS CodeBuild is a continuous integration testing service.

This PR adds a few of the CodeBuild provided environment variables that might be interesting in a pytest-html report.

### CODE REVIEW

**Review by BeyondEvil — CHANGES_REQUESTED** [review]
Awesome! Thank you for your contribution!

Mind adding the changes and a shout-out to yourself in the [changelog](https://github.com/pytest-dev/pytest-metadata/blob/master/CHANGES.rst) as well?

**Comment by dougch** [comment]
> Awesome! Thank you for your contribution!
> 
> Mind adding the changes and a shout-out to yourself in the [changelog](https://github.com/pytest-dev/pytest-metadata/blob/master/CHANGES.rst) as well?

Changelog updated.  The development guide calls out bumping the version in [pyproject.toml](https://github.com/pytest-dev/pytest-metadata/blob/c7488f04103d8619845198718f1b02ae79728ceb/development.rst?plain=1#L55) but it looks like that line was removed with the move to hatch.

**Comment by BeyondEvil** [comment]
> > Awesome! Thank you for your contribution!
> > Mind adding the changes and a shout-out to yourself in the [changelog](https://github.com/pytest-dev/pytest-metadata/blob/master/CHANGES.rst) as well?
> 
> Changelog updated. The development guide calls out bumping the version in [pyproject.toml](https://github.com/pytest-dev/pytest-metadata/blob/c7488f04103d8619845198718f1b02ae79728ceb/development.rst?plain=1#L55) but it looks like that line was removed with the move to hatch.

Good catch, thanks!

**Review by BeyondEvil — APPROVED** [review]
LGTM

**Pull request merged**
