### PR TITLE
complete poetry transition

### PR DESCRIPTION
**Pull request by abn**
Following up from https://github.com/python-poetry/poetry/discussions/5345 @BeyondEvil here are the changes you will need to complete the transtition.

Additionally, I would also suggest that you relax your version constraint as it seems the package is meant to work with `pytest>=2.9.0` as per your `setup.cfg`. However, your current constraint on pytest would mean a verision `>=7.1.1,<7.2.0` would be required.

### CODE REVIEW

**Comment by BeyondEvil** [comment]
https://github.com/pytest-dev/pytest-metadata/pull/43 😛

**Comment by abn** [comment]
Ha. Beat me to it. However note [__version.py](https://github.com/pytest-dev/pytest-metadata/pull/43/files#diff-57896a9c0b8efb8024b03993e5a96452e0de46594ca7741ef490cac6267dee48) will not be handled by poetry.

**Comment by abn** [comment]
Closing for now. Feel free to salvage anything from it.

**Comment by BeyondEvil** [comment]
I really appreciate this tho!

I do have a problem, I tried publishing to test.pypi.org, and the command `poetry publish -r test-pypi` ran successfully, but nothing is showing in `test.pypi.org`

```
$ poetry config repositories.test-pypi https://test.pypi.org/legacy/ 
$ poetry config pypi-token.test-pypi <token>
$ poetry publish -r test-pypi  
Publishing pytest-metadata (2.0.1-rc0) to test-pypi
 - Uploading pytest-metadata-2.0.1rc0.tar.gz 100%
 - Uploading pytest_metadata-2.0.1rc0-py3-none-any.whl 100%
```

**Comment by abn** [comment]
This it is there -> https://test.pypi.org/project/pytest-metadata/2.0.1rc0/

**Comment by BeyondEvil** [comment]
> This it is there -> https://test.pypi.org/project/pytest-metadata/2.0.1rc0/

I guess the search function must be broken then, cause that only shows

Screenshot 2022-03-24 at 22 18 06

**Comment by abn** [comment]
It won't show pre-releases by default.

**Pull request closed without merging**
